export const data = [
  {
    id: 1,
    title: "Pizza",
    price: 10.99,
    image: "https://source.unsplash.com/400x400/?pizza",
    amount: 1,
  },
  {
    id: 2,
    title: "Burger",
    price: 8.99,
    image: "https://source.unsplash.com/400x400/?burger",
    amount: 1,
  },
  {
    id: 3,
    title: "Fries",
    price: 4.99,
    image: "https://source.unsplash.com/400x400/?fries",
    amount: 1,
  },
  {
    id: 4,
    title: "Pasta",
    price: 12.99,
    image: "https://source.unsplash.com/400x400/?pasta",
    amount: 1,
  },
  {
    id: 5,
    title: "Sandwich",
    price: 6.99,
    image: "https://source.unsplash.com/400x400/?sandwich",
    amount: 1,
  },
  {
    id: 6,
    title: "Tacos",
    price: 9.99,
    image: "https://source.unsplash.com/400x400/?tacos",
    amount: 1,
  },
  {
    id: 7,
    title: "Sushi",
    price: 15.99,
    image: "https://source.unsplash.com/400x400/?sushi",
    amount: 1,
  },
  {
    id: 8,
    title: "Salad",
    price: 7.99,
    image: "https://source.unsplash.com/400x400/?salad",
    amount: 1,
  },
  {
    id: 9,
    title: "Soup",
    price: 5.99,
    image: "https://source.unsplash.com/400x400/?soup",
    amount: 1,
  },
  {
    id: 10,
    title: "Steak",
    price: 19.99,
    image: "https://source.unsplash.com/400x400/?steak",
    amount: 1,
  },
];
